<?php

return [
    'basic' => [
        'user_limit' => 3,
        'matter_limit' => 50,
        'storage_mb' => 1024,
        'tariff_hok' => false,
        'document_templates' => false,
        'document_versioning' => false,
        'time_approval' => false,
        'client_portal' => false,
        'e_invoice' => false,
        'calendar_sync' => false,
        'email_intake' => false,
        'esign' => false,
    ],
    'standard' => [
        'user_limit' => 15,
        'matter_limit' => 500,
        'storage_mb' => 10240,
        'tariff_hok' => true,
        'document_templates' => true,
        'document_versioning' => true,
        'time_approval' => true,
        'client_portal' => true,
        'e_invoice' => false,
        'calendar_sync' => false,
        'email_intake' => false,
        'esign' => false,
    ],
    'premium' => [
        'user_limit' => null,
        'matter_limit' => null,
        'storage_mb' => 102400,
        'tariff_hok' => true,
        'document_templates' => true,
        'document_versioning' => true,
        'time_approval' => true,
        'client_portal' => true,
        'e_invoice' => true,
        'calendar_sync' => true,
        'email_intake' => true,
        'esign' => true,
    ],
];
