<?php

return [
    'disclaimer' => 'Izračun je pomoć pri datumu prema tablici korelacije. Dan okidača se ne broji. Ako zadnji dan padne na subotu, nedjelju ili blagdan, rok se prebacuje na prvi radni dan. Datum potvrđuje odvjetnik.',

    'rules' => [
        [
            'key' => 'civil_reply',
            'kind' => 'civil',
            'category' => null,
            'label' => 'Odgovor na tužbu',
            'trigger' => 'Zaprimanje tužbe s pozivom na odgovor',
            'amount' => 30,
            'unit' => 'days',
            'basis' => 'ZPP — obvezan odgovor na tužbu',
            'event_type' => 'other',
        ],
        [
            'key' => 'possession_subjective',
            'kind' => 'civil',
            'category' => 'Smetanje posjeda',
            'label' => 'Tužba zbog smetanja posjeda (subjektivni rok)',
            'trigger' => 'Dan saznanja za čin smetanja i počinitelja',
            'amount' => 30,
            'unit' => 'days',
            'basis' => 'ZPP — subjektivni rok za tužbu',
            'event_type' => 'other',
        ],
        [
            'key' => 'possession_objective',
            'kind' => 'civil',
            'category' => 'Smetanje posjeda',
            'label' => 'Tužba zbog smetanja posjeda (objektivni rok)',
            'trigger' => 'Dan kada je smetanje nastalo',
            'amount' => 1,
            'unit' => 'years',
            'basis' => 'ZPP — objektivni rok, nakon kojeg se gubi pravo na tužbu',
            'event_type' => 'other',
        ],
        [
            'key' => 'criminal_appeal',
            'kind' => 'criminal',
            'category' => null,
            'label' => 'Žalba protiv prvostupanjske presude',
            'trigger' => 'Zaprimanje prvostupanjske presude',
            'amount' => 15,
            'unit' => 'days',
            'basis' => 'ZKP — rok za žalbu',
            'event_type' => 'appeal_deadline',
        ],
        [
            'key' => 'criminal_private',
            'kind' => 'criminal',
            'category' => 'Kaznena djela protiv života i tijela / privatnosti',
            'label' => 'Privatna tužba',
            'trigger' => 'Saznanje za kazneno djelo i počinitelja',
            'amount' => 3,
            'unit' => 'months',
            'basis' => 'ZKP — rok za privatnu tužbu, npr. kleveta',
            'event_type' => 'other',
        ],
        [
            'key' => 'commercial_enforcement_objection',
            'kind' => 'commercial',
            'category' => 'Isplata iz trgovačkih ugovora',
            'label' => 'Prigovor na rješenje o ovrsi',
            'trigger' => 'Zaprimanje rješenja o ovrsi na temelju vjerodostojne isprave',
            'amount' => 8,
            'unit' => 'days',
            'basis' => 'OZ — rok za prigovor u trgovačkim stvarima',
            'event_type' => 'objection_deadline',
        ],
        [
            'key' => 'commercial_assembly',
            'kind' => 'commercial',
            'category' => 'Pobijanje odluka skupštine / Nadzornog odbora',
            'label' => 'Tužba za pobijanje odluke skupštine',
            'trigger' => 'Donošenje ili saznanje za odluku skupštine',
            'amount' => 30,
            'unit' => 'days',
            'basis' => 'ZTD — rok za tužbu',
            'event_type' => 'other',
        ],
        [
            'key' => 'labor_zzp',
            'kind' => 'labor',
            'category' => 'Nedopuštenost otkaza ugovora o radu',
            'label' => 'Zahtjev za zaštitu prava poslodavcu',
            'trigger' => 'Zaprimanje odluke o otkazu ili saznanje za povredu',
            'amount' => 14,
            'unit' => 'days',
            'basis' => 'ZOR — zahtjev za zaštitu prava',
            'event_type' => 'other',
        ],
        [
            'key' => 'labor_lawsuit',
            'kind' => 'labor',
            'category' => 'Nedopuštenost otkaza ugovora o radu',
            'label' => 'Tužba sudu nakon zahtjeva za zaštitu prava',
            'trigger' => 'Odbijanje ili istjek šutnje poslodavca',
            'amount' => 15,
            'unit' => 'days',
            'basis' => 'ZOR — rok za tužbu. Drugi rok ne kreće sam: unesite datum odbijanja ili dan isteka šutnje.',
            'event_type' => 'other',
        ],
        [
            'key' => 'enforcement_objection',
            'kind' => 'enforcement',
            'category' => 'Ovrha na temelju vjerodostojne isprave',
            'label' => 'Prigovor na rješenje o ovrsi',
            'trigger' => 'Zaprimanje rješenja o ovrsi od javnog bilježnika',
            'amount' => 8,
            'unit' => 'days',
            'basis' => 'OZ — rok za prigovor u građanskim stvarima',
            'event_type' => 'objection_deadline',
        ],
        [
            'key' => 'admin_lawsuit',
            'kind' => 'administrative',
            'category' => null,
            'label' => 'Tužba Upravnom sudu',
            'trigger' => 'Zaprimanje konačnog rješenja drugostupanjskog tijela',
            'amount' => 30,
            'unit' => 'days',
            'basis' => 'ZUS — rok za tužbu',
            'event_type' => 'other',
        ],
        [
            'key' => 'procurement_appeal',
            'kind' => 'administrative',
            'category' => 'Javna nabava (postupci pred DKOM-om)',
            'label' => 'Žalba Državnoj komisiji',
            'trigger' => 'Objava odluke o odabiru ili poništenju u EOJN',
            'amount' => 10,
            'unit' => 'days',
            'basis' => 'ZJN — rok za žalbu',
            'event_type' => 'appeal_deadline',
        ],
    ],
];
